// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xcdvebywamyfpoeebgwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjZHZlYnl3YW15ZnBvZWViZ3doIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2OTA1MTgsImV4cCI6MjA2OTI2NjUxOH0.vPftE3HfYv12b0NX9cpYu4T7iIZGY1a1wao9hmfM9tY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});